#!/bin/bash
while true; do
ffmpeg -y -f x11grab -r 30 -s 1920x1080 -i :0.0 -t 15 -c:v libx264 -preset ultrafast -crf 23 /media/rog/C/Downloads/TV/screen.mp4
sleep 15
done

# ffmpeg -f x11grab -probesize 100M -r 60 -s 1920x1080 -i :0.0 -f pulse -ac 2 -i default -c:v h264 -preset ultrafast -tune zerolatency -pix_fmt yuv420p -vf "format=yuv420p" -c:a aac -b:a 128k -f mpegts rtsp://192.168.1.101:1057
# rtmp://192.168.1.101/video/screen
