#!/usr/bin/env bash
folder_of_script=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
#. "$folder_of_script/proxy.sh"

# To update run this:
yt-dlp -U || python3 -m pip install --force-reinstall yt-dlp --break-system-package
# sudo apt install axel
# sudo apt install aria2c aria2
# sudo apt install proxychains4

echo -en "\n===========\nTo split chapters you can use --split-chapters\n=========\n"
split=""
ARG_VALUE=""
# Parse arguments
for arg in "$@"; do
    case $arg in
        --split-chapters)
            split="--split-chapters"
            ;;
        *)
            ARG_VALUE+=("$arg")
            ;;
    esac
done

yt-dlp \
 --no-check-certificates \
 --paths temp:/tmp -N 8 \
 --cookies-from-browser firefox \
 --no-part \
 --embed-chapters --embed-thumbnail --add-metadata --embed-subs \
 --external-downloader aria2c --external-downloader-args "--check-certificate=false -j 16 -x 16 --file-allocation=none -c" \
 --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.366" \
 -ciw \
 --youtube-include-dash-manifest \
 --min-filesize 50k --ignore-errors --yes-playlist \
 --continue --extract-audio --audio-format mp3 $split ${ARG_VALUE[@]} || echo -en \
 "\n======================\nIf you need to use a proxy\nTry to use p ydl 'URL'\np is an alias for proxychains4 -q -f ~/bin/proxychain.conf\n"
#--proxy $proxy_socks5 \
