#!/usr/bin/env bash
# ============================
# let's use some colors :)
# ============================
path_of_here=$(dirname "$0")
source "${path_of_here}/colors.sh"
#===========================
## --no-osd-bar makes the mpv
## to prevent show the seek-bar
## when pressing the arrow-keys
echo -e "${txtgrn}Mpv is gonna play $@ ${resetcolor}"
/usr/bin/mpv --input-ipc-server=/tmp/mpvsocket --player-operation-mode=pseudo-gui --sub-color="#F5E741" --config-dir="${path_of_here}/mpv_" --osc=yes --no-osd-bar --sub-font="Comic Helvetic" --loop=yes "$@" # "$@"
echo -e "${txtblu}The End of file $@ ${resetcolor}"
