#!/usr/bin/env bash
# You can change messages
connect='V2Ray وصل شد'
disconnect="V2Ray قطع شد"

messages=("${connect}" "${disconnect}")
tmpFile=~/.v2raystatus       # Temporary file to set the warp status inside it
touch "${tmpFile}"           # Create it, if it's not existed yet
warpStatus=$(cat ${tmpFile}) # Read the file and store its value inside a variable

function notify {
	if [ -x "$(command -v notify-send)" ]; then
		notify-send "$1"
	else
		kdialog --passivepopup "$1" 5
	fi
	~/bin/say "${1}"
}

if [[ ${warpStatus} -eq 0 ]]; then
	systemctl start v2raya
	notify "${messages[0]}"
	echo 1 >"${tmpFile}"
else
	systemctl stop v2raya
	notify "${messages[1]}"
	echo 0 >"${tmpFile}"
fi
