#!/bin/bash
aria2c --all-proxy="http://127.0.0.1:20701" -c --download-result=default -j 28 -x 16 -s 28 -k 1M -U "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "$@"
