#!/usr/bin/env bash
# =========== Variables ===============
folder_of_script=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
main_folder="$folder_of_script/../.."
. "$folder_of_script/helper.sh"
# ========== Applications =============
clearLog
# ============ Startup ================
msg "Start Loading..."
run dunst -conf "${main_folder}/dunstrc"
run xfsettingsd --daemon -D
 # start polkit agent from lxde (sudo apt install lxpolkit)
sleep 3 && run dbus-launch lxpolkit
sleep 3 && runAsRoot dnscrypt-proxy -config "${main_folder}/dnscrypt.toml" 
# run xfce4-panel -d
run nm-applet
# run "$folder_of_script/qtile/saati/keyring.sh"
# run oblivion
run nm-tray
# run volumeicon # this uses alsa
run pasystray
run nitrogen --restore
run dropbox start
# run proxychains4-daemon
run firefox
# run gtk-launch discord
# run "/home/sdsaati/Downloads/Logseq-linux-x64-0.10.9.AppImage" --no-sandbox
# run gtk-launch Obsidian.desktop
run blueman-applet
