#!/usr/bin/env bash
# =========== Variables ===============
folder_of_script=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
main_folder="$folder_of_script/../.."
. "$folder_of_script/helper.sh"
clearLog
# ============ Startup ================
run picom --config "$main_folder/picom/picom.conf"
run xgamma -gamma 1.5
run setxkbmap -option ctrl:nocaps
msg "Welcome! Everything Loaded."
