#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    bootstrap_after = 'file#after'
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "gruvbox"
    colorscheme = "SpaceVim"
    # colorscheme = "one"
    # colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "arrow"

    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # this will makes 's' does what it does in normal vim
    windows_leader = ''
    guifont = "MonaSpiceNe Nerd Font Mono:h11"
    escape_key_binding = 'jk'

[[layers]]
name = "fzf"

[[layers]]
name = 'autocomplete'
auto-completion-delay = 10
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "git"

[[layers]]
name = "lang#python"
# make sure that you installed these:
# pip install flake8 black mypy pylint pylsp django
enable_typeinfo = true
format_on_save = true
enabled_linters = ['python', 'pylint']

[[layers]]
name = 'framework#django'

[[layers]]
  name = 'lsp'
  enabled_clients = ['pylsp']

[[layers]]
name = "colorscheme"

[[layers]]
name = "ui"
enable_scrollbar = true



