#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  bootstrap_after = 'startup#after'
  bootstrap_before = 'startup#before'
# the value can be `leaderguide` or `whichkey`
  # leader_guide_theme = 'leaderguide'
  search_tools = ["rg", "ag", "grep"]
  # filemanager = "nerdtree"
  enable_filetree_gitstatus = true
  enable_vimfiler_welcome = true
  filetree_direction = "left"
  search_highlight_persist=true
  enable_persist_flygrep = true
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
  # colorscheme = "desert"
  # colorscheme = "space_vim_theme"
  # colorscheme = "OceanicNext"
  # colorscheme = "gruvbox"
  # colorscheme = "SpaceVim"
  # colorscheme = "srcery"
  # colorscheme = "nord"
  # colorscheme = "blue"
  # colorscheme = "hybrid"
  # colorscheme = "jellybeans"
  colorscheme = "onedark"
  # colorscheme = "molokai"
  # colorscheme = "material"
  # colorscheme = "NeoSolarized"
  # colorscheme = "dracula"
  # colorscheme = "one"
  # colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
# possible values for seperators: curve, nil, arrow, fire, slant
  statusline_separator = "nil"
  statusline_iseparator = "nil"
  relativenumber = false
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true
# this will makes 's' does what it does in normal vim
  windows_leader = ''
  guifont = "ZedMono Nerd Font:h11"
  escape_key_binding = 'jk'

[[layers]]
  name = "fzf"
[[layers]]
  name = "ssh"
  ssh_user = 'root'
  ssh_address = '195.62.33.46'
  ssh_port = '22'
[[layers]]
  name = "test"
[[layers]]
  name = 'tools#mpv'
  # mpv_interpreter = 'D:\Program Files\mpv\mpv.exe'
  musics_directory = '~/Music'

[[layers]]
   name = "colorscheme"

[[layers]]
   name = "ui"
   enable_scrollbar = false

[[layers]]
  name = "tools#cpicker"

[[layers]]
  name = 'autocomplete'
  auto-completion-delay = 10
  auto_completion_return_key_behavior = "smart"
  auto_completion_tab_key_behavior = "smart"
  autocomplete_method = "completor"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "git"

[[layers]]
  name = "lang#python"
# make sure that you installed these:
# pip install flake8 black mypy pylint pylsp django
  enable_typeinfo = true
  format_on_save = true
  enabled_linters = ['python', 'pylint']
[[layers]]
  name = "lang#java"
[[layers]]
  name = "lang#markdown"
[[layers]]
  name = "lang#javascript"
[[layers]]
  name = "lang#latex"
[[layers]]
  name = "lang#json"
[[layers]]
  name = "lang#html"
[[layers]]
  name = "lang#go"
[[layers]]
  name = "lang#dart"
[[layers]]
  name = "lang#csharp"
[[layers]]
  name = "lang#cmake"
[[layers]]
  name = "lang#c"
[[layers]]
  name = "lang#kotlin"
[[layers]]
  name = "lang#rust"
[[layers]]
  name = "lang#toml"
[[layers]]
  name = "lang#vim"
[[layers]]
  name = "lang#vue"
[[layers]]
  name = "lang#xml"
[[layers]]
  name = "lang#php"
[[layers]]
  name = "lang#plantuml"
[[layers]]
  name = 'lsp'
  enabled_clients = ['pylsp']
[[layers]]
name = "ctrlspace"
[[layers]]
  name = 'framework#django'

[[layers]]
  name = "treesitter"


[[custom_plugins]]
  repo = "liuchengxu/vista.vim"

[[custom_plugins]] 
  repo = "lilydjwg/colorizer"


[[custom_plugins]]
  repo = 'liuchengxu/space-vim-theme'
  merged = 0
[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = 0

