name: go test
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 17 * * 1'  # https://crontab.guru/#0_17_*_*_1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,  windows-latest, macos-latest]
        js: [false]
        include:
          - os: ubuntu-latest
            js: true
    steps:
      - id: go-test
        uses: djherbis/actions/go-test@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coveralls_parallel: true
        if: ${{ !matrix.js }}
      - id: go-test-js
        uses: djherbis/actions/go-test-js@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coveralls_parallel: true
        if: ${{ matrix.js }}
  finish:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: shogo82148/actions-goveralls@v1
          with:
            parallel-finished: true
