if status is-interactive
    # Commands to run in interactive sessions can go here
    set fish_greeting
end
set fish_key_bindings fish_user_key_bindings
fish_add_path -p ~/bin
set -x PATH "/home/$(whoami)/bin:/home/$(whoami)/.fzf/bin:$PATH"
# set -x colorls_theme "--dark"
set -x RANGER_LOAD_DEFAULT_RC FALSE
set -x BAT_THEME "Dracula"
set -x ANDROID_EMULATOR_USE_SYSTEM_LIBS 1
set -x JAVA_HOME ""
set -x EDITOR "vim"
set -x fzf_theme "--color=16"
set -x FZF_DEFAULT_OPTS "--preview 'batcat --color=always {}'"
set -x FZF_DEFAULT_COMMAND "rg --files --hidden --smart-case --follow --glob \"!.*__pycache__/*\" --glob \"!venv/*\" --glob \"!.venv/*\" --glob \"!.git/*\""
set -x SUDO_ASKPASS (which ssh-askpass)
alias vim="nvim.appimage"
alias winpy="wine64 /home/$(whoami)/.wine/drive_c/Python310/python.exe"
alias ls="colorls $colorls_theme --hyperlink"
alias ll="colorls $colorls_theme -lh --hyperlink"
alias la="colorls $colorls_theme -lah --hyperlink"
alias m="systemctl restart minidlna"
alias tree="tree -a -I .git"
alias fzf="fzf $fzf_theme"
alias fcd="cd (dirname (fzf))"
alias ping="ping -nc4"
alias cat="batcat"
alias rm="rm -rf"
alias gl="git log --oneline --decorate"
alias gs="git status"
alias gaAll="git add -A"
alias ga="git add"
alias gc="git commit"
alias gr="git rm"
alias grOnlyFromGit="git rm --cached"
alias gm="git mv"
alias gunstage="git restore --staged"
alias gamend="git commit --amend"
alias gdiscard="git restore"
alias gclone="git clone"
alias gpullOriginMain="git pull origin main"
alias gpullOriginMaster="git pull origin master"
alias gpushOriginMain="git push origin main"
alias gpushOriginMaster="git push origin master"
alias gtagList="git tag -l"
alias gtagCreate="git tag -a"
alias gshow="git show"
alias p="proxychains4 -q -f ~/bin/proxychain.conf"
alias ag="ag --search-binary -f --hidden --no-group --ignore='*.m4a' --ignore='*.webm' --ignore='*.flatpak' --ignore='*.deb' --ignore='*.appimage' --ignore='*.mp4' --ignore='*.mkv' --ignore='*.mp3' --ignore='*.iso'"
